import json
import os
from datetime import datetime, timedelta
from typing import Dict, List
from config import BLOG_URL, AUTHOR_NAME

class ReportGenerator:
    def __init__(self, publish_log: List[Dict], content_stats: Dict, approval_stats: Dict):
        self.publish_log = publish_log
        self.content_stats = content_stats
        self.approval_stats = approval_stats
    
    def generate_daily_report(self, date: str = None) -> str:
        if not date:
            date = datetime.now().strftime('%Y-%m-%d')
        
        report = f"# Daily Report - {date}\n\n"
        report += f"Generated at: {datetime.now().isoformat()}\n"
        report += f"Generated by: {AUTHOR_NAME}\n\n"
        
        report += self._generate_publish_section()
        report += self._generate_content_section()
        report += self._generate_approval_section()
        report += self._generate_summary()
        
        return report
    
    def generate_weekly_report(self, week_start: str = None) -> str:
        if not week_start:
            today = datetime.now()
            week_start = (today - timedelta(days=today.weekday())).strftime('%Y-%m-%d')
        
        report = f"# Weekly Report - {week_start}\n\n"
        report += f"Generated at: {datetime.now().isoformat()}\n"
        report += f"Generated by: {AUTHOR_NAME}\n\n"
        
        report += self._generate_publish_section(weekly=True)
        report += self._generate_content_section()
        report += self._generate_approval_section()
        report += self._generate_trend_analysis()
        report += self._generate_summary()
        
        return report
    
    def _generate_publish_section(self, weekly: bool = False) -> str:
        section = "## Publication Performance\n\n"
        
        total_published = sum(1 for log in self.publish_log if log['success'])
        total_failed = sum(1 for log in self.publish_log if not log['success'])
        total_attempts = len(self.publish_log)
        
        success_rate = (total_published / total_attempts * 100) if total_attempts > 0 else 0
        
        section += f"| Metric | Value |\n"
        section += f"|--------|-------|\n"
        section += f"| Total Attempts | {total_attempts} |\n"
        section += f"| Successful | {total_published} |\n"
        section += f"| Failed | {total_failed} |\n"
        section += f"| Success Rate | {success_rate:.1f}% |\n\n"
        
        section += "### By Platform\n\n"
        by_platform = {}
        for log in self.publish_log:
            platform = log['platform']
            if platform not in by_platform:
                by_platform[platform] = {'success': 0, 'failed': 0}
            
            if log['success']:
                by_platform[platform]['success'] += 1
            else:
                by_platform[platform]['failed'] += 1
        
        section += f"| Platform | Published | Failed | Success Rate |\n"
        section += f"|----------|-----------|--------|--------------|\n"
        
        for platform, stats in by_platform.items():
            total = stats['success'] + stats['failed']
            rate = (stats['success'] / total * 100) if total > 0 else 0
            section += f"| {platform.capitalize()} | {stats['success']} | {stats['failed']} | {rate:.1f}% |\n"
        
        section += "\n"
        
        if total_failed > 0:
            section += "### Failed Posts\n\n"
            failed_logs = [log for log in self.publish_log if not log['success']]
            
            for log in failed_logs[:5]:
                section += f"- **{log['content_title']}** ({log['platform']}): {log.get('error', 'Unknown error')}\n"
        
        return section
    
    def _generate_content_section(self) -> str:
        section = "## Content Library\n\n"
        
        section += f"| Metric | Value |\n"
        section += f"|--------|-------|\n"
        section += f"| Total Content | {self.content_stats.get('total', 0)} |\n"
        section += f"| Last Updated | {self.content_stats.get('updated_at', 'N/A')} |\n\n"
        
        section += "### Content by Source\n\n"
        by_source = self.content_stats.get('by_source', {})
        if by_source:
            section += f"| Source | Count | Percentage |\n"
            section += f"|--------|-------|------------|\n"
            
            total = self.content_stats.get('total', 1)
            for source, count in by_source.items():
                percentage = (count / total * 100)
                section += f"| {source} | {count} | {percentage:.1f}% |\n"
        
        section += "\n"
        
        section += "### Content by Topic\n\n"
        by_topic = self.content_stats.get('by_topic', {})
        if by_topic:
            topics = sorted(by_topic.items(), key=lambda x: x[1], reverse=True)[:10]
            
            section += f"| Topic | Count |\n"
            section += f"|-------|-------|\n"
            
            for topic, count in topics:
                section += f"| {topic} | {count} |\n"
        
        return section + "\n"
    
    def _generate_approval_section(self) -> str:
        section = "## Approval Queue\n\n"
        
        pending = self.approval_stats.get('pending', 0)
        approved = self.approval_stats.get('approved', 0)
        rejected = self.approval_stats.get('rejected', 0)
        total = pending + approved + rejected
        
        section += f"| Status | Count |\n"
        section += f"|--------|-------|\n"
        section += f"| Pending | {pending} |\n"
        section += f"| Approved | {approved} |\n"
        section += f"| Rejected | {rejected} |\n"
        section += f"| Total | {total} |\n\n"
        
        return section
    
    def _generate_trend_analysis(self) -> str:
        section = "## Trend Analysis\n\n"
        
        daily_counts = {}
        for log in self.publish_log:
            date = log['timestamp'][:10]
            daily_counts[date] = daily_counts.get(date, 0) + 1
        
        if daily_counts:
            section += "### Daily Publication Trend\n\n"
            section += f"| Date | Posts |\n"
            section += f"|------|-------|\n"
            
            for date, count in sorted(daily_counts.items()):
                section += f"| {date} | {count} |\n"
        
        return section + "\n"
    
    def _generate_summary(self) -> str:
        section = "## Summary\n\n"
        
        total_published = sum(1 for log in self.publish_log if log['success'])
        pending = self.approval_stats.get('pending', 0)
        total_content = self.content_stats.get('total', 0)
        
        section += f"- **Total published this period**: {total_published}\n"
        section += f"- **Pending approvals**: {pending}\n"
        section += f"- **Content in library**: {total_content}\n"
        section += f"- **Blog**: [{BLOG_URL}]({BLOG_URL})\n\n"
        
        section += "---\n"
        section += "*This report was automatically generated by the ChinaBound Travel Social Bot*\n"
        
        return section
    
    def save_report(self, report: str, filename: str = None):
        if not filename:
            filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(report)
        
        return filename

class AnalyticsDashboard:
    def __init__(self, scheduler):
        self.scheduler = scheduler
    
    def get_dashboard_data(self) -> Dict:
        return {
            'publish_stats': self.scheduler.get_stats(),
            'content_stats': self.scheduler.content_manager.get_stats(),
            'approval_stats': {
                'pending': len(self.scheduler.get_pending_approvals()),
                'approved': sum(1 for a in self.scheduler.approval_queue if a['status'] == 'approved'),
                'rejected': sum(1 for a in self.scheduler.approval_queue if a['status'] == 'rejected')
            },
            'recent_posts': self.scheduler.get_publish_log(limit=10)
        }
    
    def print_dashboard(self):
        data = self.get_dashboard_data()
        
        print("\n" + "="*60)
        print("         ChinaBound Travel Analytics Dashboard")
        print("="*60)
        
        print("\n[Publication Stats]")
        print("-" * 40)
        ps = data['publish_stats']
        print(f"  Total Published: {ps['total_published']}")
        print(f"  Total Failed: {ps['total_failed']}")
        print(f"  Pending Approvals: {ps['pending_approvals']}")
        
        print("\n[Content Library]")
        print("-" * 40)
        cs = data['content_stats']
        print(f"  Total Content: {cs['total']}")
        
        print("\n[Approval Status]")
        print("-" * 40)
        as_ = data['approval_stats']
        print(f"  Pending: {as_['pending']}")
        print(f"  Approved: {as_['approved']}")
        print(f"  Rejected: {as_['rejected']}")
        
        print("\n[Recent Posts]")
        print("-" * 40)
        for post in data['recent_posts']:
            status = "[OK]" if post['success'] else "[FAIL]"
            print(f"  {status} {post['platform']}: {post['content_title'][:40]}...")
        
        print("\n" + "="*60 + "\n")
    
    def generate_and_save_daily_report(self):
        data = self.get_dashboard_data()
        generator = ReportGenerator(
            self.scheduler.get_publish_log(),
            data['content_stats'],
            data['approval_stats']
        )
        
        report = generator.generate_daily_report()
        filename = generator.save_report(report)
        print(f"Daily report saved to: {filename}")
        
        return filename
    
    def generate_and_save_weekly_report(self):
        data = self.get_dashboard_data()
        generator = ReportGenerator(
            self.scheduler.get_publish_log(),
            data['content_stats'],
            data['approval_stats']
        )
        
        report = generator.generate_weekly_report()
        filename = generator.save_report(report)
        print(f"Weekly report saved to: {filename}")
        
        return filename

if __name__ == '__main__':
    from publisher import PublicationScheduler
    
    scheduler = PublicationScheduler()
    dashboard = AnalyticsDashboard(scheduler)
    
    dashboard.print_dashboard()
    
    daily_file = dashboard.generate_and_save_daily_report()
    weekly_file = dashboard.generate_and_save_weekly_report()
    
    print(f"\nReports generated:\n- {daily_file}\n- {weekly_file}")